# Generated by Django 4.1.4 on 2023-09-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorgy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=False, help_text='0=defualt,1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=defualt,1=Hidden')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=False, help_text='0=defualt,1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=defualt,1=Hidden')),
                ('description', models.CharField(max_length=500)),
                ('quanty', models.IntegerField()),
                ('orignalprice', models.FloatField()),
                ('sellingprice', models.FloatField()),
                ('categorgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extra.categorgy')),
            ],
        ),
    ]
